###
POST http://localhost:4000/api/pacientes HTTP/1.1
Content-Type: application/json


{
  "nhc": "500343894839",
  "codigo": "A-342",
  "apellidoPaterno": "Martinez",
  "apellidoMaterno": "Rodriguez",
  "nombres": "Marcos",
  "edad": 34,
  "sexo": "M",
  "lugarNacimiento": "Cochabamba",
  "fechaNacimiento": "2002-11-09",
  "ocupacion": "estudiante",
  "direccion": "calle 123",
  "celular": "78765432"
}

###
GET http://localhost:4000/api/pacientes HTTP/1.1

###
GET http://localhost:4000/api/pacientes/6358d4b7e53f054af11ec5bf HTTP/1.1

###
PUT http://localhost:4000/api/pacientes/636b4edfa34ffad4427bea65 HTTP/1.1
Content-Type: application/json

{
  
  "habitos": "fuma",
  "higieneDental": "no",
  "respirador": "bucal"
}

###
DELETE http://localhost:4000/api/pacientes/6358d539e53f054af11ec5ca HTTP/1.1

###
POST http://localhost:4000/api/dentistas HTTP/1.1
Content-Type: application/json


{
  "nombre": "Katherin Calatayud",
  "especialidad": "Odontopediatra",
  "listaPacientes": []
}

###
GET http://localhost:4000/api/dentistas HTTP/1.1

###
GET http://localhost:4000/api/dentistas/6358d4b7e53f054af11ec5bf HTTP/1.1

###
PUT http://localhost:4000/api/dentistas/636b49aedf53d17e54de9b7f HTTP/1.1
Content-Type: application/json

{
  "nhc": "100343894839",
  "codigo": "A-342",
  "respirador": "nasal",
}

###
DELETE http://localhost:4000/api/pacientes/6358d539e53f054af11ec5ca HTTP/1.1


###
POST http://localhost:4000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "Katherin@gmail.com",
  "password": "123abc"
}

###
POST http://localhost:4000/api/signup HTTP/1.1
Content-Type: application/json

{
  "email": "Katherin@gmail.com",
  "password": "123abc"
}